### PR TITLE
Check if release mode or not with kReleaseMode

### PR DESCRIPTION
**Pull request by ctrleffive**
You can use assert() method to check if the code is running in debug mode or not. assert() method only execute in debug mode.

### CODE REVIEW

**Comment by ibhavikmakwana** [comment]
Hi @ctrleffive, Do you have any specific example or any link to the doc?
As there is one already tip on the Assertion.
And this might not be the best way to do so.

**Comment by ibhavikmakwana** [comment]
Actual way is to use the `kReleaseMode` from the foundation library.

**Comment by ctrleffive** [comment]
> Hi @ctrleffive, Do you have any specific example or any link to the doc?

I've been using this in my projects.
https://github.com/ctrleffive/music-stories/blob/master/lib/main.dart
Have a look here.

> As there is one already tip on the Assertion.
> And this might not be the best way to do so.

I didn't know about this. I'll close the PR. Thank you!

**Comment by ibhavikmakwana** [comment]
Hey,
You should update a PR,
Using a kReleaseMode is also a Tip for Flutter devs.

**Comment by ctrleffive** [comment]
ok ill do

**Review by ibhavikmakwana — APPROVED** [review]

**Pull request merged**
